In [49]:
from typing import Literal

import pandas as pd
import polars as pl

import sourmash

In [3]:
! ls -lha /home/ec2-user/kmerseek/tests/testdata/fasta/

total 652K
drwxr-xr-x. 4 ec2-user ec2-user  16K Feb  7 20:40 .
drwxr-xr-x. 4 ec2-user ec2-user   32 Feb  6 02:19 ..
-rw-r--r--. 1 ec2-user ec2-user 6.5K Feb  6 01:23 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
-rw-r--r--. 1 ec2-user ec2-user  41K Feb  8 00:26 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
-rw-r--r--. 1 ec2-user ec2-user 416K Feb  8 00:41 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.kmers.csv
drwxr-xr-x. 2 ec2-user ec2-user  16K Feb  7 20:48 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.rocksdb
-rw-r--r--. 1 ec2-user ec2-user  140 Feb  7 20:48 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.siglist
-rw-r--r--. 1 ec2-user ec2-user  41K Feb  6 02:21 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k24.scaled5.sig.zip
-rw-r--r--. 1 ec2-user ec2-user 9.7K Feb  6 02:21 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k24.scaled5.sig.zip.kmers.csv
drwxr-xr-x. 2 ec2-user ec2-user  159 Feb  6 02:21 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k24.scaled5.sig.zip.rocksdb
-rw-r--r--. 1 ec2-user ec2-user  140 Feb  6 02:21 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k24.scaled5.sig.zip.siglist
-rw-r--r--. 1 ec2-user ec2-user  230 Feb  8 00:26 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.manysketch.csv
-rw-r--r--. 1 ec2-user ec2-user  385 Feb  6 01:23 ced9.fasta
-rw-r--r--. 1 ec2-user ec2-user 1.6K Feb  7 20:39 ced9.fasta.hp.k15.scaled5.sig.zip
-rw-r--r--. 1 ec2-user ec2-user 9.9K Feb  6 02:33 ced9.fasta.hp.k15.scaled5.sig.zip.kmers.csv
-rw-r--r--. 1 ec2-user ec2-user   78 Feb  7 20:39 ced9.fasta.hp.k15.scaled5.sig.zip.siglist
-rw-r--r--. 1 ec2-user ec2-user  106 Feb  7 20:39 ced9.fasta.manysketch.csv
-rw-r--r--. 1 ec2-user ec2-user  55K Feb  6 01:23 uniprotkb_BCL2_AND_model_organism_9606_2025_02_06.fasta.gz

In [4]:
! ls -lha /home/ec2-user/kmerseek/tests/testdata/index/

total 96K
drwxr-xr-x. 3 ec2-user ec2-user  16K Feb  7 20:26 .
drwxr-xr-x. 4 ec2-user ec2-user   32 Feb  6 02:19 ..
-rw-r--r--. 1 ec2-user ec2-user 6.5K Feb  7 19:54 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
-rw-r--r--. 1 ec2-user ec2-user  41K Feb  7 20:39 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
-rw-r--r--. 1 ec2-user ec2-user  14K Feb  6 02:18 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.kmers.csv
drwxr-xr-x. 2 ec2-user ec2-user  159 Feb  6 02:18 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.rocksdb
-rw-r--r--. 1 ec2-user ec2-user  148 Feb  7 20:26 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.rocksdb.siglist
-rw-r--r--. 1 ec2-user ec2-user  140 Feb  7 20:39 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.siglist
-rw-r--r--. 1 ec2-user ec2-user  230 Feb  7 20:39 bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.manysketch.csv

In [5]:
len("hphhphhhhhhhhpp")

15

In [6]:
len("GRFLKAAFFVLLPER")

15

In [7]:
! rm -rf bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.kmers.csv

In [8]:
! sourmash sig describe /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip

== This is sourmash version 4.8.11. ==
== Please cite Irber et. al (2024), doi:10.21105/joss.06830. ==

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|O43236|SEPT4_HUMAN Septin-4 OS=Homo sapiens OX=9606 GN=SEPTIN4 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: f3f2c84e928c964e3217762e3d687983
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 90
sum hashes: 90
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|O43521|B2L11_HUMAN Bcl-2-like protein 11 OS=Homo sapiens OX=9606 GN=BCL2L11 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 2edcfc90413e5fb3663a34f57fb37947
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 34
sum hashes: 34
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|O60238|BNI3L_HUMAN BCL2/adenovirus E1B 19 kDa protein-interacting protein 3-like OS=Homo sapiens OX=9606 GN=BNIP3L PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 3f173239c5108bbf6290a6dc7dfce4af
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 27
sum hashes: 27
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapiens OX=9606 GN=RTN3 PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 45126f9076669e6d8d6294b48477db81
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 185
sum hashes: 189
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|P10415|BCL2_HUMAN Apoptosis regulator Bcl-2 OS=Homo sapiens OX=9606 GN=BCL2 PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 3a0addc51b19012d4bed489c792916ba
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 43
sum hashes: 43
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|P98170|XIAP_HUMAN E3 ubiquitin-protein ligase XIAP OS=Homo sapiens OX=9606 GN=XIAP PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 43f2f2fc7a93069426bc6f44c852936c
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 89
sum hashes: 91
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q07812|BAX_HUMAN Apoptosis regulator BAX OS=Homo sapiens OX=9606 GN=BAX PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 0a9e3dcb2827546102fe574c06727f9d
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 23
sum hashes: 23
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q07817|B2CL1_HUMAN Bcl-2-like protein 1 OS=Homo sapiens OX=9606 GN=BCL2L1 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 945edee666fb806ddf257bd0b019b7d0
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 52
sum hashes: 52
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q07820|MCL1_HUMAN Induced myeloid leukemia cell differentiation protein Mcl-1 OS=Homo sapiens OX=9606 GN=MCL1 PE=1 SV=3
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 740d9e28a17f5afae96823b2c437c7ac
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 77
sum hashes: 81
signature license: CC0

---<<<236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip' / 10 sigs total
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q12981|SEC20_HUMAN Vesicle transport protein SEC20 OS=Homo sapiens OX=9606 GN=BNIP1 PE=1 SV=3
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 3426aa682124d58f427cca7e1fc1e7c4
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 43
sum hashes: 43
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 kDa protein-interacting protein 2 OS=Homo sapiens OX=9606 GN=BNIP2 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 2358d8aaf2c1d88299f65e5d8edd590d
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 58
sum hashes: 58
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q12983|BNIP3_HUMAN BCL2/adenovirus E1B 19 kDa protein-interacting protein 3 OS=Homo sapiens OX=9606 GN=BNIP3 PE=1 SV=4
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 2e59102568adcfdf7488b91c20017a07
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 36
sum hashes: 36
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q13625|ASPP2_HUMAN Apoptosis-stimulating of p53 protein 2 OS=Homo sapiens OX=9606 GN=TP53BP2 PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 22fd2a2911cb005695f6b7c0ac0aabbc
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 168
sum hashes: 172
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q14318|FKBP8_HUMAN Peptidyl-prolyl cis-trans isomerase FKBP8 OS=Homo sapiens OX=9606 GN=FKBP8 PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: ec0424dd141cae02263762eeb5ce7f63
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 82
sum hashes: 83
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q14457|BECN1_HUMAN Beclin-1 OS=Homo sapiens OX=9606 GN=BECN1 PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 64aee70cc99df19902e71f80d31ae4e8
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 75
sum hashes: 76
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q16548|B2LA1_HUMAN Bcl-2-related protein A1 OS=Homo sapiens OX=9606 GN=BCL2A1 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: ff61a140759fb9890283bbf068ed66aa
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 37
sum hashes: 37
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q16611|BAK_HUMAN Bcl-2 homologous antagonist/killer OS=Homo sapiens OX=9606 GN=BAK1 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: ab8cbb12fa9911aecf251411a1dd256a
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 34
sum hashes: 34
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q92843|B2CL2_HUMAN Bcl-2-like protein 2 OS=Homo sapiens OX=9606 GN=BCL2L2 PE=1 SV=2
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 5b6b5d25a990ebe554702c611e580248
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 41
sum hashes: 42
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q92934|BAD_HUMAN Bcl2-associated agonist of cell death OS=Homo sapiens OX=9606 GN=BAD PE=1 SV=3
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 8101005601ad9c4fefba7cd870aba7d8
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 32
sum hashes: 33
signature license: CC0

---<<<236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip' / 20 sigs total
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q9BXH1|BBC3_HUMAN Bcl-2-binding component 3, isoforms 1/2 OS=Homo sapiens OX=9606 GN=BBC3 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 31999c1484485bb243cbec55e80678fa
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 33
sum hashes: 33
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q9BXK5|B2L13_HUMAN Bcl-2-like protein 13 OS=Homo sapiens OX=9606 GN=BCL2L13 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 0cf3bb57845032ad7c4cf4a28e21c55b
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 102
sum hashes: 112
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q9BZR8|B2L14_HUMAN Apoptosis facilitator Bcl-2-like protein 14 OS=Homo sapiens OX=9606 GN=BCL2L14 PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: b76e4143f71a5df3f9d90fff69113aa7
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 62
sum hashes: 62
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q9HD36|B2L10_HUMAN Bcl-2-like protein 10 OS=Homo sapiens OX=9606 GN=BCL2L10 PE=1 SV=3
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 81893b90fc003e234dd6f17f3df01a81
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 36
sum hashes: 36
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS=Homo sapiens OX=9606 GN=FBXO10 PE=1 SV=3
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 468951fd02a6ba58fd3a0635368b9de8
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 177
sum hashes: 180
signature license: CC0

---
signature filename: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
signature: sp|Q9UMX3|BOK_HUMAN Bcl-2-related ovarian killer protein OS=Homo sapiens OX=9606 GN=BOK PE=1 SV=1
source file: /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
md5: 25ad9c79cef25e251066c74c19e10ba3
k=15 molecule=hp num=0 scaled=5 seed=42 track_abundance=1
size: 37
sum hashes: 37
signature license: CC0

loaded 25 signatures total, from 1 filesr/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip'

In [45]:
from kmerseek.sig2kmer import encode_protein

ModuleNotFoundError: No module named 'sourmash_plugin_branchwater'

In [46]:
# TODO: maybe add this to sourmash.sig.__main__.kmers because it's useful to us,
# could be useful to others
def encode_protein(sequence, moltype):
    """Convert protein sequence from 20-letter amino acid alphabet to degenerate alphabet"""
    # Pre-determine the alphabet function based on moltype
    if moltype == "hp":
        alphabet_func = sourmash._lowlevel.lib.sourmash_aa_to_hp
    elif moltype == "dayhoff":
        alphabet_func = sourmash._lowlevel.lib.sourmash_aa_to_dayhoff
    else:
        raise ValueError(f"Unknown moltype: {moltype}")

    # Convert the entire sequence to bytes once
    byte_sequence = sequence.encode("utf-8")

    # Apply the alphabet function to each byte in the sequence and join the result
    degenerate = b"".join(
        alphabet_func(letter.to_bytes(1, "big")) for letter in byte_sequence
    ).decode()

    return degenerate

In [48]:
def add_encoding_to_kmers_pd(
    csv_in: str, moltype: Literal["hp", "dayhoff"], csv_out: str
):
    kmers = pd.read_csv(csv_in)
    kmers["encoded"] = kmers["kmer"].apply(lambda x: encode_protein(x, moltype))
    return kmers


def add_encoding_to_kmers_pl(
    csv_in: str, moltype: Literal["hp", "dayhoff"], csv_out: str
):
    kmers = pl.scan_csv(csv)

    # Apply encoding using a UDF (User Defined Function)
    kmers_with_encoding = kmers.with_columns(
        pl.col("kmer").map_elements(encode_protein).alias("encoded")
    )

    kmers.sink_csv(csv_out)

    return kmers

NameError: name 'Literal' is not defined

In [51]:
query_kmers = pl.read_csv(
    "/home/ec2-user/kmerseek/tests/testdata/fasta/ced9.fasta.hp.k15.scaled5.sig.zip.kmers.csv"
)
query_kmers

shape: (47, 4)
┌───────────────────────────────────┬──────────────────────┬─────────────────┬─────────────────────┐
│ sequence_file                     ┆ sequence_name        ┆ kmer            ┆ hashval             │
│ ---                               ┆ ---                  ┆ ---             ┆ ---                 │
│ str                               ┆ str                  ┆ str             ┆ i64                 │
╞═══════════════════════════════════╪══════════════════════╪═════════════════╪═════════════════════╡
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ CTADNSLTNPAYRRR ┆ 1151751887590685437 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ LTNPAYRRRTMATGE ┆ 416728349327701565  │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ RRRTMATGEMKEFLG ┆ 340975793795730804  │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ TGEMKEFLGIKGTEP ┆ 3518051877631019118 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ KGTEPTDFGINSDAQ ┆ 3194303753598287434 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ …                                 ┆ …                    ┆ …               ┆ …                   │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ NRSWDDFMTLGKQMK ┆ 3187426618721885528 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ RSWDDFMTLGKQMKE ┆ 1640735000939443109 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ KEDYERAEAEKVGRR ┆ 682542044277166603  │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ ERAEAEKVGRRKQNR ┆ 3344088491490275285 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
│ /home/ec2-user/kmerseek/tests/…   ┆ sp|P41958|CED9_CAEEL ┆ GVTAGAIGIVGVVVC ┆ 1680845944460923601 │
│                                   ┆ Apoptosis…           ┆                 ┆                     │
└───────────────────────────────────┴──────────────────────┴─────────────────┴─────────────────────┘

In [55]:
query_kmers = pd.read_parquet(
    "/home/ec2-user/kmerseek/tests/testdata/fasta/ced9.fasta.hp.k15.scaled5.sig.zip.kmers.pq"
)
print(query_kmers.shape)
query_kmers.head()

(47, 5)

,sequence_file,sequence_name,kmer,hashval,encoded
0,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,CTADNSLTNPAYRRR,1151751887590685437,pphppphpphhhppp
1,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,LTNPAYRRRTMATGE,416728349327701565,hpphhhpppphhphp
2,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,RRRTMATGEMKEFLG,340975793795730804,pppphhphphpphhh
3,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,TGEMKEFLGIKGTEP,3518051877631019118,phphpphhhhphpph
4,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,KGTEPTDFGINSDAQ,3194303753598287434,phpphpphhhppphp

In [34]:
ls /home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz*

/home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz
/home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip
/home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.siglist
/home/ec2-user/kmerseek/tests/testdata/index/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.manysketch.csv

In [57]:
target_kmers = pd.read_parquet(
    "/home/ec2-user/kmerseek/tests/testdata/fasta/bcl2_first25_uniprotkb_accession_O43236_OR_accession_2025_02_06.fasta.gz.hp.k15.scaled5.sig.zip.kmers.pq"
)
print(target_kmers.shape)
target_kmers.head()

(1704, 5)

,sequence_file,sequence_name,kmer,hashval,encoded
0,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O43236|SEPT4_HUMAN Septin-4 OS=Homo sapiens...,QGNSVPEDRTEAGIK,373490021111495450,phpphhppppphhhp
1,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O43236|SEPT4_HUMAN Septin-4 OS=Homo sapiens...,GNSVPEDRTEAGIKR,2766956208440184639,hpphhppppphhhpp
2,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O43236|SEPT4_HUMAN Septin-4 OS=Homo sapiens...,SVPEDRTEAGIKRFL,3240525533884903831,phhppppphhhpphh
3,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O43236|SEPT4_HUMAN Septin-4 OS=Homo sapiens...,VPEDRTEAGIKRFLE,1564803042480469903,hhppppphhhpphhp
4,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O43236|SEPT4_HUMAN Septin-4 OS=Homo sapiens...,TEAGIKRFLEDTTDD,3074595715241908351,pphhhpphhpppppp

In [60]:
query_kmers.merge(target_kmers, on=["hashval"])

,sequence_file_x,sequence_name_x,kmer_x,hashval,encoded_x,sequence_file_y,sequence_name_y,kmer_y,encoded_y
0,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,STRRMSIGESIDGKI,298650496001980560,pppphphhpphphph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapie...,TTENPKLPSTVSPNV,pppphphhpphphph
1,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,STRRMSIGESIDGKI,298650496001980560,pppphphhpphphph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,ECRHPNWPNQPDVEP,pppphphhpphphph
2,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,TRRMSIGESIDGKIN,2019447628595610669,ppphphhpphphphp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,CRHPNWPNQPDVEPE,ppphphhpphphphp
3,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,SIGESIDGKINDWEE,1238682245839468867,phhpphphphpphpp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,NWPNQPDVEPESWRE,phhpphphphpphpp
4,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,ESIDGKINDWEEPRL,1148619785672034840,pphphphpphpphph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P98170|XIAP_HUMAN E3 ubiquitin-protein liga...,EKIQISGSNYKSLEV,pphphphpphpphph
5,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,LDIEGFVVDYFTHRI,2510495965372635344,hphphhhhphhppph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,IEADILAITGPEDQP,hphphhhhphhppph
6,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,RIRQNGMEWFGAPGL,3428762742407114906,phppphhphhhhhhh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9HD36|B2L10_HUMAN Bcl-2-like protein 10 OS...,QIHRSFFSAYLGYPG,phppphhphhhhhhh
7,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,QPEHEMMRVMGTIFE,2863698201823062072,phppphhphhhphhp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q92843|B2CL2_HUMAN Bcl-2-like protein 2 OS=...,QVSDELFQGGPNWGR,phppphhphhhphhp
8,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,EHEMMRVMGTIFEKK,1748401096767941120,ppphhphhhphhppp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapie...,DDTLAELPGSPPEKC,ppphhphhhphhppp
9,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,VMGTIFEKKHAENFE,2050028938048683095,hhhphhpppphpphp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q14457|BECN1_HUMAN Beclin-1 OS=Homo sapiens...,PPARMMSTESANSFT,hhhphhpppphpphp
10,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,QCPMSYGRLIGLISF,2474282513327167724,pphhphhphhhhhph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P10415|BCL2_HUMAN Apoptosis regulator Bcl-2...,RDGVNWGRIVAFFEF,pphhphhphhhhhph
11,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,QCPMSYGRLIGLISF,2474282513327167724,pphhphhphhhhhph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q07817|B2CL1_HUMAN Bcl-2-like protein 1 OS=...,RDGVNWGRIVAFFSF,pphhphhphhhhhph
12,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,CPMSYGRLIGLISFG,873697441541549083,phhphhphhhhhphh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P10415|BCL2_HUMAN Apoptosis regulator Bcl-2...,DGVNWGRIVAFFEFG,phhphhphhhhhphh
13,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,CPMSYGRLIGLISFG,873697441541549083,phhphhphhhhhphh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q07817|B2CL1_HUMAN Bcl-2-like protein 1 OS=...,DGVNWGRIVAFFSFG,phhphhphhhhhphh
14,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,SYGRLIGLISFGGFV,3128169917091194898,phhphhhhhphhhhh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P10415|BCL2_HUMAN Apoptosis regulator Bcl-2...,NWGRIVAFFEFGGVM,phhphhhhhphhhhh
15,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,SYGRLIGLISFGGFV,3128169917091194898,phhphhhhhphhhhh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q07817|B2CL1_HUMAN Bcl-2-like protein 1 OS=...,NWGRIVAFFSFGGAL,phhphhhhhphhhhh
16,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,SYGRLIGLISFGGFV,3128169917091194898,phhphhhhhphhhhh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9BXH1|BBC3_HUMAN Bcl-2-binding component 3...,CAPTAPPAVTAALGG,phhphhhhhphhhhh
17,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,SYGRLIGLISFGGFV,3128169917091194898,phhphhhhhphhhhh,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,QGPRPVLGGSFLGPP,phhphhhhhphhhhh
18,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,VRNLFVYTSLFIKTR,2834299149737369899,hpphhhhpphhhppp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,IRTLLAVTRPFISSK,hpphhhhpphhhppp
19,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,RNLFVYTSLFIKTRI,3030830621314638391,pphhhhpphhhppph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,RTLLAVTRPFISSKF,pphhhhpphhhppph
20,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,NLFVYTSLFIKTRIR,3629945976886609934,phhhhpphhhppphp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P98170|XIAP_HUMAN E3 ubiquitin-protein liga...,KWYPGCKYLLEQKGQ,phhhhpphhhppphp
21,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,NLFVYTSLFIKTRIR,3629945976886609934,phhhhpphhhppphp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,TLLAVTRPFISSKFS,phhhhpphhhppphp
22,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,LFVYTSLFIKTRIRN,987187089471598728,hhhhpphhhppphpp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P98170|XIAP_HUMAN E3 ubiquitin-protein liga...,WYPGCKYLLEQKGQE,hhhhpphhhppphpp
23,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,LFVYTSLFIKTRIRN,987187089471598728,hhhhpphhhppphpp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,LLAVTRPFISSKFSQ,hhhhpphhhppphpp
24,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,KTRIRNNWKEHNRSW,1409469941104901431,ppphppphpppppph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapie...,DKEFKDSYKESTDDF,ppphppphpppppph
25,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,GVTAGAIGIVGVVVC,1680845944460923601,hhphhhhhhhhhhhp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q16611|BAK_HUMAN Bcl-2 homologous antagonis...,ILNVLVVLGVVLLGQ,hhphhhhhhhhhhhp
26,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,GVTAGAIGIVGVVVC,1680845944460923601,hhphhhhhhhhhhhp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q92843|B2CL2_HUMAN Bcl-2-like protein 2 OS=...,WGRLVAFFVFGAALC,hhphhhhhhhhhhhp

In [ ]:
target_

In [61]:
def merge_kmers(query, target):
    merge_on = ["encoded", "hashval"]

    merged_kmers = query.merge(
        target,
        left_on=merge_on,
        right_on=merge_on,
        suffixes=("_query", "_match"),
        how="inner",
    )
    return merged_kmers


merged_kmers = merge_kmers(query_kmers, target_kmers)
print(merged_kmers.shape)
merged_kmers.head()

(27, 8)

,sequence_file_query,sequence_name_query,kmer_query,hashval,encoded,sequence_file_match,sequence_name_match,kmer_match
0,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,STRRMSIGESIDGKI,298650496001980560,pppphphhpphphph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapie...,TTENPKLPSTVSPNV
1,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,STRRMSIGESIDGKI,298650496001980560,pppphphhpphphph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,ECRHPNWPNQPDVEP
2,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,TRRMSIGESIDGKIN,2019447628595610669,ppphphhpphphphp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,CRHPNWPNQPDVEPE
3,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,SIGESIDGKINDWEE,1238682245839468867,phhpphphphpphpp,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,NWPNQPDVEPESWRE
4,/home/ec2-user/kmerseek/tests/testdata/fasta/c...,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,ESIDGKINDWEEPRL,1148619785672034840,pphphphpphpphph,/home/ec2-user/kmerseek/tests/testdata/fasta/b...,sp|P98170|XIAP_HUMAN E3 ubiquitin-protein liga...,EKIQISGSNYKSLEV

## Query kmer freq

In [79]:
def get_kmer_freq(kmer_df):
    # kmer_counts = kmer_df["hashval"].value_counts()
    kmer_counts = kmer_df.groupby("hashval").size()
    kmer_freq = kmer_counts / kmer_counts.sum()
    return kmer_freq


query_kmer_freq = get_kmer_freq(query_kmers)
query_kmer_freq.head()

hashval
70153183367952091     0.021277
298650496001980560    0.021277
340975793795730804    0.021277
368750771736920820    0.021277
374307737455824216    0.021277
dtype: float64

In [80]:
target_kmer_freq = get_kmer_freq(target_kmers).sort_values(ascending=False)
target_kmer_freq.head()

hashval
2138476190321946888    0.008803
3193831626143463474    0.002934
3128169917091194898    0.002347
3187705093364853506    0.002347
982220801608548857     0.002347
dtype: float64

# Manysearch

In [74]:
manysearch = pd.read_csv(
    "/home/ec2-user/kmerseek/ced9-bcl2-first25.manysearch.csv"
).sort_values("intersect_hashes", ascending=False)
print(manysearch.shape)
manysearch.head()

(11, 20)

,query_name,query_md5,match_name,containment,intersect_hashes,ksize,scaled,moltype,match_md5,jaccard,max_containment,average_abund,median_abund,std_abund,query_containment_ani,match_containment_ani,average_containment_ani,max_containment_ani,n_weighted_found,total_weighted_hashes
8,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,0.106383,5,45,5,hp,2358d8aaf2c1d88299f65e5d8edd590d,0.050000,0.106383,1.0,1.0,0.0,0.951426,0.946990,0.949208,0.951426,5,58
10,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,0.085106,4,45,5,hp,468951fd02a6ba58fd3a0635368b9de8,0.018182,0.085106,1.0,1.0,0.0,0.946720,0.919230,0.932975,0.946720,4,180
0,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|P10415|BCL2_HUMAN Apoptosis regulator Bcl-2...,0.063830,3,45,5,hp,3a0addc51b19012d4bed489c792916ba,0.034483,0.069767,1.0,1.0,0.0,0.940687,0.942548,0.941617,0.942548,3,43
5,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapie...,0.063830,3,45,5,hp,45126f9076669e6d8d6294b48477db81,0.013100,0.063830,1.0,1.0,0.0,0.940687,0.912475,0.926581,0.940687,3,189
4,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|P98170|XIAP_HUMAN E3 ubiquitin-protein liga...,0.063830,3,45,5,hp,43f2f2fc7a93069426bc6f44c852936c,0.022556,0.063830,1.0,1.0,0.0,0.940687,0.927434,0.934060,0.940687,3,91

In [86]:
for i, row in manysearch.iterrows():
    target_match_kmers = target_kmers.query("sequence_name == @row.match_name")
    query_match_kmers = query_kmers.query("sequence_name == @row.query_name")

    overlapping_hashes = target_match_kmers.hashval[target_match_kmers.hashval.isin(query_match_kmers.hashval)]

    prob_overlap = (
        target_kmer_freq[overlapping_hashes] * query_kmer_freq[overlapping_hashes]
    ).sum()
    break

In [87]:
prob_overlap

np.float64(8.740385575866547e-05)

# Multisearch

In [63]:
multisearch = pd.read_csv(
    "/home/ec2-user/kmerseek/ced9-bcl2-first25.multisearch.csv"
).sort_values("intersect_hashes", ascending=False)
print(multisearch.shape)
multisearch.head()

(11, 16)

,query_name,query_md5,match_name,match_md5,containment,max_containment,jaccard,intersect_hashes,ksize,scaled,moltype,prob_overlap,prob_overlap_adjusted,containment_adjusted,containment_adjusted_log10,tf_idf_score
6,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|Q12982|BNIP2_HUMAN BCL2/adenovirus E1B 19 k...,2358d8aaf2c1d88299f65e5d8edd590d,0.106383,0.106383,0.050000,5.0,45,5,hp,0.000087,0.002185,48.685714,1.687402,0.361996
10,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|Q9UK96|FBX10_HUMAN F-box only protein 10 OS...,468951fd02a6ba58fd3a0635368b9de8,0.085106,0.085106,0.018182,4.0,45,5,hp,0.000100,0.002497,34.080000,1.532500,0.275277
7,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|P10415|BCL2_HUMAN Apoptosis regulator Bcl-2...,3a0addc51b19012d4bed489c792916ba,0.063830,0.069767,0.034483,3.0,45,5,hp,0.000100,0.002497,25.560000,1.407561,0.190801
8,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|P98170|XIAP_HUMAN E3 ubiquitin-protein liga...,43f2f2fc7a93069426bc6f44c852936c,0.063830,0.063830,0.022556,3.0,45,5,hp,0.000062,0.001561,40.896000,1.611681,0.210296
9,sp|P41958|CED9_CAEEL Apoptosis regulator ced-9...,1e928a47193b683a34eb5130da49344e,sp|O95197|RTN3_HUMAN Reticulon-3 OS=Homo sapie...,45126f9076669e6d8d6294b48477db81,0.063830,0.063830,0.013100,3.0,45,5,hp,0.000050,0.001249,51.120000,1.708591,0.218923